name: Build and test Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { OS: "linux", ARCH: "386", ARM: "" }
          - { OS: "linux", ARCH: "amd64", ARM: "" }
          - { OS: "linux", ARCH: "arm", ARM: "5" }
          - { OS: "linux", ARCH: "arm", ARM: "6" }
          - { OS: "linux", ARCH: "arm", ARM: "7" }
          - { OS: "linux", ARCH: "arm64", ARM: "" }
          - { OS: "darwin", ARCH: "amd64", ARM: "" }
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Go test
        run: make check

      - name: Build
        run: make build OS=${{ matrix.OS }} ARCH=${{ matrix.ARCH }} ARM=${{ matrix.ARM }}
